apiVersion: v1
kind: Secret
metadata:  
  name: sql-password
type: Opaque
data:
  SQL_PASSWORD: ZkwwcXAzR283
  SQL_SERVER: c3Fsc2VydmVyYmVnNjEwOS5kYXRhYmFzZS53aW5kb3dzLm5ldA==
  SQL_USER: c3FsYWRtaW5iRWc2MTA5
  SQL_DBNAME: bXlkcml2aW5nREI=