apiVersion: v1
kind: Pod
metadata:
  labels:
    app: trips 
  name: trips
spec:
  containers:
  - env:
    - name: OPENAPI_DOCS_URI
      value: http://changeme
    image: registrybeg6109.azurecr.io/trips:v1
    imagePullPolicy: IfNotPresent
    name: trips
    volumeMounts:
      - name: sql-password
        mountPath: "/secrets"
        readOnly: true
    resources:
      limits:
        cpu: 500m
        memory: 250Mi
      requests:
        cpu: 100m
        memory: 50Mi
    ports:
      - containerPort: 80
  volumes:
    - name: sql-password
      secret:
        secretName: sql-password
  dnsPolicy: ClusterFirst
  restartPolicy: Always